---
- name: Ensure the apt cache is updated
  apt: >
    update_cache=yes

- name: Install primary apt repositories
  apt_repository: >
    repo="ppa:pithos/ppa"
    update_cache=yes

- name: Ensure basic packages are installed
  apt: >
    name={{ item }}
    state=latest
  with_items: "{{ basic_packages }}"

- name: Ensure recommended packages are installed
  apt: >
    name={{ item }}
    state=latest
  with_items: "{{ recommended_packages }}"

- name: Ensure Git is configured
  command: >
    git config --global {{ item.config }} "{{ item.value }}"
  become: yes
  become_user: "{{ current_username }}"
  with_items:
    - config: user.email
      value: behrangsa@gmail.com
    - config: user.name
      value: Behrang Saeedzadeh

# - name: Install JetBrains Toolbox
# - name: Install SSH Keys
# - name: Install Arc-OSX-Icons
# - name: Install OSX-Arc-Darker
# - name: Install Opera
# - name: Install Docker
#   with_items:
#     - neo4j
#     - orientdb
#     - postgresql
#     - rabbitmq
# - Install GPG keys
# - Install Maven
# - Install Conky
# - Run update-pepperflashplugin-nonfree --install
# - Wallpaper
# - Login Screen

